### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by wendyHYR** [Erfan-Shooraj/ifc2b3dm#3]
Hello,
I tried to use your code 'GLTFs2B3DM'.But, the following errors are occurred.
Unhandled rejection TypeError: Cannot read property 'KHR_materials_common' of undefined
    at Function.Material.fromGltf (C:\Users\wendy\Desktop\ifc2b3dm-master\ifc2b3dm-master\GLTFs2B3DM\lib\Material.js:40:37)
    at Function.Mesh.fromGltf (C:\Users\wendy\Desktop\ifc2b3dm-master\ifc2b3dm-master\GLTFs2B3DM\lib\Mesh.js:295:29)
    at C:\Users\wendy\Desktop\ifc2b3dm-master\ifc2b3dm-master\GLTFs2B3DM\lib\createBatchTableHierarchy.js:126:42
    at <anonymous>
So, how can i solve this problem?

Thanks.

**Comment by Erfan-Shooraj** [comment]
Hi,
Obj2gltf has removed the --materialsCommon flag and has replaced it with --materialsUnlit. I will change the code later to adapt to the newer versions.

In the meantime, you can use an older version of obj2gltf like version 2.0.0 and it should solve your problem.

**Comment by wendyHYR** [comment]
@Erfan-Shooraj 
Thanks for your quick response.
This problem has been solved. But, a new problem has arisen. 
I can use your code to convert my model from gltf to b3dm. But, the tileset is too small and also i can't  load it into Cesium.
I think some mistakes are appeared from gltf to b3dm, but no errors are displayed in my cmd. So, can you help me solve this problem or can you provide me your BIM model?
![image](https://user-images.githubusercontent.com/41276109/54199586-40bfad00-4504-11e9-9f80-c35599d0a284.png)
![image](https://user-images.githubusercontent.com/41276109/54199557-2dacdd00-4504-11e9-964a-1c553cf507e8.png)
![image](https://user-images.githubusercontent.com/41276109/54199664-6f3d8800-4504-11e9-9e7f-d0bc6f051fe5.png)
![image](https://user-images.githubusercontent.com/41276109/54199689-84b2b200-4504-11e9-8b77-cab32e20a838.png)

**Comment by Erfan-Shooraj** [comment]
Since you're tileset is too small, I think it's because your gltf files don't have the geometry information in them and they're practically blank. Can you view each gltf file with the windows viewer or a program like open3mod?
If the gltf files don't open, or you can't view them, it must be a problem with prior stages.
You can trace back by trying to see if you can view the IFC files with something like open3mod or Solibri. Same with objs.
If the problem is with the IFC files, I should mention when I tried to query objects with BimServer and IFC4 files, I had similar issues. So try to check in IFC2x3 files if that is your problem. Sometimes the querying issue happened even with IFC2x3, so a restart of the server or re-checking in the model might help.
I think I can help you better if you let me know at which stage you lose the geometry and can't view it.

**Comment by wendyHYR** [comment]
I got it. Thanks.
