### ISSUE TITLE
material of gltf  disappear after converting to b3dm

### ISSUE THREAD

**Issue by BL961118** [Erfan-Shooraj/ifc2b3dm#9]
The  material in gltf  file is described like this:
"materials": [
    {
      "name": "surface_style_43_默�_楼板",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.588,
          0.588,
          0.588,
          1
        ],
        "metallicFactor": 0,
        "roughnessFactor": 0.99
      },
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "alphaMode": "OPAQUE",
      "doubleSided": false
    }
  ],
In the gltf view-tool,it appears "red"color ,but after converting it to b3dm,the color disappear.
I hope you can give me some guides.Thank you very much.

**Comment by Erfan-Shooraj** [comment]
Is your gltf file from an IFC file or are you just using the GLTFS2B3DM step?

Because the IFC2GLTFs step uses the "--materialsCommon" flag (now modified to "--unlit" flag) for obj2gltf which does not produce gltf files with PBR materials. I suggest you use this flag and run the converter again because it does not support PBR materials.

**Comment by BL961118** [comment]
Thank you for your help.I have understood it.
